[programs.localnet]
somos_solana = "Hy5hYwxnZXNFJv8rvKkLRGmM4eBRnpFC1Wc9TxcELeXB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/mocha/bin/mocha -t 1000000 tests/"
