[programs.localnet]
somos_solana = "FffriA7x24t4EqEvov8rxEctNmedxirN4WevtvRkHCyA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/mocha/bin/mocha -t 1000000 tests/"
