[programs.localnet]
somos_solana = "BLWVpsSBzbUWx7vyacCt8r4RL5cq5oVGXsAFc68MygtA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/mocha/bin/mocha -t 1000000 tests/"
